### ISSUE TITLE
Option to choose between Github and Gitlab

### ISSUE THREAD

**Issue by devbyray** [jeroenouw/cgx#1]
**Is your feature request related to a problem? Please describe.**
It would be nice to generate files for Github and Gitlab.

For example for:
- Issue templates https://docs.gitlab.com/ee/user/project/description_templates.html
- Gitlab-ci.yml https://docs.gitlab.com/ee/ci/yaml/README.html

**Describe the solution you'd like**
Pick your Git hosting provider
> Github
> Gitlab

**Comment by jeroenouw** [comment]
Resolved in [1.2.0](https://github.com/jeroenouw/cgx/releases/tag/v1.2.0)
